services:
  postgres:
    image: postgres:15
    container_name: cex-postgres
    restart: always
    environment:
      POSTGRES_USER: cex
      POSTGRES_PASSWORD: cexpass
      POSTGRES_DB: cexdb
    ports:
      - "5432:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
